name       : python-websockets
version    : '10.1'
release    : 5
source     :
    - https://files.pythonhosted.org/packages/source/w/websockets/websockets-10.1.tar.gz : 181d2b25de5a437b36aefedaf006ecb6fa3aa1328ec0236cdde15f32f9d3ff6d
license    : BSD-3-Clause
component  : programming.python
summary    : An implementation of the WebSocket Protocol (RFC 6455 & 7692)
description: |
    websockets is a library for building WebSocket servers and clients in Python with a focus on correctness and simplicity. Built on top of asyncio, Python's standard asynchronous I/O framework, it provides an elegant coroutine-based API.
builddeps  :
    - pkgconfig(python3)
build      : |
    %python3_setup
install    : |
    %python3_install
