name       : python-websockets
version    : 8.0.2
release    : 3
source     :
    - https://files.pythonhosted.org/packages/79/78/17e97a159dc55308b1468a638c7267f19765281f6205ec9c15253c154022/websockets-8.0.2.tar.gz : 882a7266fa867a2ebb2c0baaa0f9159cabf131cf18c1b4270d79ad42f9208dc5
license    : BSD-3-Clause
component  : programming.python
summary    : An implementation of the WebSocket Protocol (RFC 6455 & 7692)
description: |
    websockets is a library for building WebSocket servers and clients in Python with a focus on correctness and simplicity. Built on top of asyncio, Python's standard asynchronous I/O framework, it provides an elegant coroutine-based API.
builddeps  :
    - pkgconfig(python3)
    - python-pytest
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
